/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TopoprintsApi from "../../../../index";
/**
 * @example
 *     {}
 */
export interface SearchPlantsByStatusRequest {
    /**
     * The status of plants to search for.
     */
    status?: TopoprintsApi.SearchPlantsByStatusRequestStatus;
}
