/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type SearchPlantsByStatusRequestStatus = "available" | "pending" | "sold";
export declare const SearchPlantsByStatusRequestStatus: {
    readonly Available: "available";
    readonly Pending: "pending";
    readonly Sold: "sold";
};
