"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SearchPlantsByStatusRequestStatus = void 0;
exports.SearchPlantsByStatusRequestStatus = {
    Available: "available",
    Pending: "pending",
    Sold: "sold",
};
