/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TopoprintsApi from "../index";
export interface Plant {
    name?: string;
    category?: string;
    tags?: string[];
    status?: TopoprintsApi.PlantStatus;
}
