"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TopoprintsApiTimeoutError = void 0;
class TopoprintsApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, TopoprintsApiTimeoutError.prototype);
    }
}
exports.TopoprintsApiTimeoutError = TopoprintsApiTimeoutError;
