"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TopoprintsApiClient = void 0;
const Client_1 = require("./api/resources/plant/client/Client");
const Client_2 = require("./api/resources/user/client/Client");
class TopoprintsApiClient {
    constructor(_options = {}) {
        this._options = _options;
    }
    get plant() {
        var _a;
        return ((_a = this._plant) !== null && _a !== void 0 ? _a : (this._plant = new Client_1.Plant(this._options)));
    }
    get user() {
        var _a;
        return ((_a = this._user) !== null && _a !== void 0 ? _a : (this._user = new Client_2.User(this._options)));
    }
}
exports.TopoprintsApiClient = TopoprintsApiClient;
