/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const TopoprintsApiEnvironment: {
    readonly Default: "https://api.plantstore.dev/v3";
};
export declare type TopoprintsApiEnvironment = typeof TopoprintsApiEnvironment.Default;
