/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as TopoprintsApi from "../../api/index";
import * as core from "../../core";
import { PlantStatus } from "./PlantStatus";
export declare const Plant: core.serialization.ObjectSchema<serializers.Plant.Raw, TopoprintsApi.Plant>;
export declare namespace Plant {
    interface Raw {
        name?: string | null;
        category?: string | null;
        tags?: string[] | null;
        status?: PlantStatus.Raw | null;
    }
}
