/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as TopoprintsApi from "../../../index";
export declare namespace User {
    interface Options {
        environment?: core.Supplier<environments.TopoprintsApiEnvironment | string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
    }
}
/**
 * Operations about user
 */
export declare class User {
    protected readonly _options: User.Options;
    constructor(_options?: User.Options);
    /**
     * @param {TopoprintsApi.LoginUserRequest} request
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.loginUser()
     */
    loginUser(request?: TopoprintsApi.LoginUserRequest, requestOptions?: User.RequestOptions): Promise<TopoprintsApi.UserAuthResponse>;
    /**
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.logoutUser()
     */
    logoutUser(requestOptions?: User.RequestOptions): Promise<void>;
    /**
     * Retrieve user details using their username.
     *
     * @param {string} username - Username of the user to retrieve
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.getUserByName("username")
     */
    getUserByName(username: string, requestOptions?: User.RequestOptions): Promise<TopoprintsApi.User>;
}
