/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { Plant } from "./api/resources/plant/client/Client";
import { User } from "./api/resources/user/client/Client";
export declare namespace TopoprintsApiClient {
    interface Options {
        environment?: core.Supplier<environments.TopoprintsApiEnvironment | string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
    }
}
export declare class TopoprintsApiClient {
    protected readonly _options: TopoprintsApiClient.Options;
    constructor(_options?: TopoprintsApiClient.Options);
    protected _plant: Plant | undefined;
    get plant(): Plant;
    protected _user: User | undefined;
    get user(): User;
}
