# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .plant_status import PlantStatus
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class Plant(UniversalBaseModel):
    name: typing.Optional[str] = None
    category: typing.Optional[str] = None
    tags: typing.Optional[typing.List[str]] = None
    status: typing.Optional[PlantStatus] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
