/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as TopoprintsApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const SearchPlantsByStatusRequestStatus: core.serialization.Schema<serializers.SearchPlantsByStatusRequestStatus.Raw, TopoprintsApi.SearchPlantsByStatusRequestStatus>;
export declare namespace SearchPlantsByStatusRequestStatus {
    type Raw = "available" | "pending" | "sold";
}
