/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as TopoprintsApi from "../../../../api/index";
import * as core from "../../../../core";
import { PlantResponse } from "../../../types/PlantResponse";
export declare const Response: core.serialization.Schema<serializers.plant.searchPlantsByStatus.Response.Raw, TopoprintsApi.PlantResponse[]>;
export declare namespace Response {
    type Raw = PlantResponse.Raw[];
}
