/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as TopoprintsApi from "../../api/index";
import * as core from "../../core";
export declare const User: core.serialization.ObjectSchema<serializers.User.Raw, TopoprintsApi.User>;
export declare namespace User {
    interface Raw {
        id?: number | null;
        username?: string | null;
        email?: string | null;
    }
}
