/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as TopoprintsApi from "../../../index";
export declare namespace Plant {
    interface Options {
        environment?: core.Supplier<environments.TopoprintsApiEnvironment | string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
    }
}
/**
 * Everything about your Plants
 */
export declare class Plant {
    protected readonly _options: Plant.Options;
    constructor(_options?: Plant.Options);
    /**
     * @param {TopoprintsApi.Plant} request
     * @param {Plant.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TopoprintsApi.MethodNotAllowedError}
     *
     * @example
     *     await client.plant.addPlant({
     *         name: "Fern",
     *         category: "Indoor",
     *         tags: ["green", "leafy"],
     *         status: TopoprintsApi.PlantStatus.Available
     *     })
     */
    addPlant(request: TopoprintsApi.Plant, requestOptions?: Plant.RequestOptions): Promise<TopoprintsApi.PlantResponse>;
    /**
     * @param {TopoprintsApi.Plant} request
     * @param {Plant.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TopoprintsApi.BadRequestError}
     * @throws {@link TopoprintsApi.NotFoundError}
     *
     * @example
     *     await client.plant.updatePlant({
     *         name: "Fern",
     *         category: "Indoor",
     *         tags: ["green", "leafy"],
     *         status: TopoprintsApi.PlantStatus.Sold
     *     })
     */
    updatePlant(request: TopoprintsApi.Plant, requestOptions?: Plant.RequestOptions): Promise<TopoprintsApi.PlantResponse>;
    /**
     * Filter plants based on their current status.
     *
     * @param {TopoprintsApi.SearchPlantsByStatusRequest} request
     * @param {Plant.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.searchPlantsByStatus()
     */
    searchPlantsByStatus(request?: TopoprintsApi.SearchPlantsByStatusRequest, requestOptions?: Plant.RequestOptions): Promise<TopoprintsApi.PlantResponse[]>;
    /**
     * Filter plants based on associated tags.
     *
     * @param {TopoprintsApi.SearchPlantsByTagsRequest} request
     * @param {Plant.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.searchPlantsByTags()
     */
    searchPlantsByTags(request?: TopoprintsApi.SearchPlantsByTagsRequest, requestOptions?: Plant.RequestOptions): Promise<TopoprintsApi.PlantResponse[]>;
    /**
     * Retrieve a plant's details by its ID.
     *
     * @param {number} plantId - ID of the plant to retrieve
     * @param {Plant.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.getPlantById(1)
     */
    getPlantById(plantId: number, requestOptions?: Plant.RequestOptions): Promise<TopoprintsApi.PlantResponse>;
}
